[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of a ROS client library"
license = "MIT"
name = "rosrust"
readme = "README.md"
repository = "https://github.com/adnanademovic/rosrust"
version = "0.5.1"

[dependencies]
byteorder = "1.2.1"
error-chain = "0.11.0"
futures = "0.1.17"
itertools = "0.7.4"
lazy_static = "1.0.0"
log = "0.3.8"
nix = "0.9.0"
regex = "0.2.3"
rust-crypto = "0.2.36"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_rosmsg = "0.2.0"
xml-rpc = "0.0.7"
yaml-rust = "0.4.0"
