[package]
edition = "2018"
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of a ROS client library"
license = "MIT"
name = "rosrust"
readme = "../README.md"
repository = "https://github.com/adnanademovic/rosrust"
version = "0.8.0"

[dependencies]
byteorder = "1.2.3"
ctrlc = "3.0.3"
error-chain = "0.11.0"
lazy_static = "1.0.0"
log = "0.4.0"
nix = "0.9.0"
rosrust_codegen = "0.8.0"
serde = "1.0.25"
serde_derive = "1.0.25"
xml-rpc = "0.0.12"
yaml-rust = "0.4.0"
crossbeam = "0.7"
net2 = "0.2.33"
colored = "1.7.0"

[dev-dependencies]
regex = "1.1.2"
criterion = "0.2.10"

[[bench]]
name = "benchmarks"
harness = false
path = "tests/benchmarks.rs"
